name: Android CI/CD

on:
  workflow_dispatch:

jobs:

  ci-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Compile project
        run: ./gradlew assembleRelease

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: build-cache
          path: |
            app/build
            gradle
            gradlew

  cd-bundle:
    needs: ci-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [qa, stg]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download build outputs
        uses: actions/download-artifact@v4
        with:
          name: build-cache

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Change environment in manifest
        run: |
          sed -i 's/android:value="qa"/android:value="${{ matrix.environment }}"/g' app/src/main/AndroidManifest.xml

      - name: Generate bundle
        run: ./gradlew bundleRelease

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.environment }}
          path: app/build/outputs/bundle/release/*.aab